name = "colors"
main = "src/index.ts"
compatibility_date = "2024-01-17"

[[r2_buckets]]
binding = 'colorsBucket' # <~ valid JavaScript variable name
bucket_name = 'colors'

[triggers]
crons = ["*/5 * * * *"] # * * * * * = run every minute